Repository oasysai/oasysdb, pull requests merged in 2024-04, with the labels that each got.

#50 feat: result relevancy threshold
  py/oasysdb/collection.pyi
  py/tests/test_collection.py
  src/func/collection.rs
  src/func/distance.rs
  src/tests/test_collection.rs
Labels: enhancement

#54 feat: add batch insert
  py/oasysdb/collection.pyi
  py/tests/test_collection.py
  src/func/collection.rs
  src/tests/mod.rs
  src/tests/test_collection.rs
Labels: enhancement

#57 feat: additional data points to readme
  bench/main.rs
  bench/utils.rs
  examples/measure-memory.rs
  readme.md
Labels: enhancement

#58 refactor: remove dead code and improve formatting
  Cargo.lock
  Cargo.toml
  bench/main.rs
  bench/utils.rs
  examples/measure-memory.rs
  readme.md
Labels: chore

#60 feat: return new vectorid after insert
  src/func/collection.rs
Labels: enhancement

#59 feat: hide pyo3 deps behind py feature
  .editorconfig
  .flake8
  .github/workflows/quality-check.yml
  Cargo.toml
  docs/contributing.md
  requirements.txt
  src/db/database.rs
  src/db/mod.rs
  src/func/collection.rs
  src/func/distance.rs
  src/func/err.rs
  src/func/metadata.rs
  src/func/mod.rs
  src/func/vector.rs
  src/lib.rs
Labels: enhancement

#63 feat: improve distance calculation
  Cargo.lock
  Cargo.toml
  src/func/distance.rs
  src/func/mod.rs
Labels: enhancement

#66 feat: improve error type implementation
  src/func/collection.rs
  src/func/distance.rs
  src/func/err.rs
Labels: enhancement

#67 fix: improve config
  py/oasysdb/collection.pyi
  py/tests/test_collection.py
  src/func/collection.rs
Labels: enhancement

#71 feat: add empty impl std error for error
  src/func/err.rs
Labels: enhancement

#73 feat: add normalized cosine distance
  py/oasysdb/collection.pyi
  src/func/distance.rs
  src/tests/test_distance.rs
Labels: enhancement

#72 feat: add conversion from json value to metadata vice versa
  .github/workflows/quality-check.yml
  Cargo.lock
  Cargo.toml
  src/func/metadata.rs
  src/tests/mod.rs
  src/tests/test_metadata.rs
Labels: enhancement

#74 feat: add collection true search benchmark
  bench/main.rs
Labels: chore

#76 feat: add vector id utility methods
  src/func/vector.rs
Labels: enhancement

#78 fix: search distance calculation
  examples/quickstart.rs
  py/tests/test_collection.py
  readme.md
  src/func/collection.rs
  src/func/utils.rs
Labels: bug

#75 docs: improve all docs
  docs/guide.md
  readme.md
Labels: chore

#80 chore: simplify oasysdb test suites
  .cargo/config.toml
  .github/workflows/quality-check.yml
  py/tests/test_database.py
  src/tests/mod.rs
  src/tests/test_collection.rs
  src/tests/test_database.rs
Labels: enhancement
